add scripts to download ABI reference atlas and convert to Nifti
IBT-FMI/mouse-brain-templates pull request #2
Opened 2018-09-06 17:51 UTC by setina42

2018-09-06 17:53 UTC, setina42 commented
Will add Registration with Ants  and Resize tomorrow

2018-09-08 21:30 UTC, TheChymera requested changes
There's a lot of blank lines here. Please follow the guidelines of one blank line to delimit units of logic (2 blank lines only between functions which have blank lines instide --- of which there are none here), and no blank lines between a comment line and the code it comments, analogous to here: https://github.com/IBT-FMI/mouse-brain-atlases/blob/aaa5ef3982850d9b842749246e3bed83bf7d3c55/ambmc.sh

2018-09-21 12:53 UTC, TheChymera requested changes

2018-09-21 12:53 UTC, TheChymera commented on Nrrd_To_Nifti.py
> +  readnrrd = nrrd.read(file)
indent with tabs, not spaces.

2018-09-22 12:32 UTC, TheChymera requested changes

2018-09-22 12:32 UTC, TheChymera commented on nrrd_to_nifti.py
> +  print("Reading " + file)
Please indent with tabs, not spaces :)

2018-09-23 22:53 UTC, merged